include $(TOPDIR)/rules.mk

LUCI_TITLE:=服务管理
LUCI_DEPENDS:=+luci-base

PKG_LICENSE:=Apache-2.0
PKG_VERSION:=1.0.6
PKG_RELEASE:=1
PKG_MAINTAINER:=OpenWrt Developer

include ../../feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
