#!/bin/sh

uci -q batch <<-EOF
	add firewall rule
	set firewall.@rule[-1].name='Allow-UUGameBooster-Input'
	set firewall.@rule[-1].src='*'
	set firewall.@rule[-1].target='ACCEPT'
	set firewall.@rule[-1].device='tun163'
	set firewall.@rule[-1].direction='in'
	add_list firewall.@rule[-1].proto='all'

	add firewall rule
	set firewall.@rule[-1].name='Allow-UUGameBooster-Forward-In'
	set firewall.@rule[-1].src='*'
	set firewall.@rule[-1].dest='*'
	set firewall.@rule[-1].target='ACCEPT'
	set firewall.@rule[-1].device='tun163'
	set firewall.@rule[-1].direction='in'
	add_list firewall.@rule[-1].proto='all'

	add firewall rule
	set firewall.@rule[-1].name='Allow-UUGameBooster-Forward-Out'
	set firewall.@rule[-1].src='*'
	set firewall.@rule[-1].dest='*'
	set firewall.@rule[-1].target='ACCEPT'
	set firewall.@rule[-1].device='tun163'
	set firewall.@rule[-1].direction='out'
	add_list firewall.@rule[-1].proto='all'

	commit firewall
EOF

/etc/init.d/firewall restart 2>/dev/null

exit 0
