include $(TOPDIR)/rules.mk

LUCI_TITLE:=全锥型 NAT (Full-cone)
LUCI_DEPENDS:=+luci-base +kmod-nft-fullcone

PKG_LICENSE:=Apache-2.0
PKG_VERSION:=1.0.0
PKG_RELEASE:=1
PKG_MAINTAINER:=OpenWrt Developer

include ../../feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
