#!/bin/sh /etc/rc.common

START=90
STOP=20

USE_PROCD=1

UUPLUGIN_BIN="/usr/bin/uuplugin"
UUPLUGIN_CONF="/usr/share/uugamebooster/uu.conf"
UUPLUGIN_PID="/var/run/uuplugin.pid"

sync_version() {
	local version
	if [ -f "$UUPLUGIN_CONF" ]; then
		version=$(grep '^version=' "$UUPLUGIN_CONF" | cut -d'=' -f2)
		[ -n "$version" ] && uci set uuplugin.status.version="$version"
	fi
	uci set uuplugin.status.running='1'
	uci commit uuplugin
}

start_service() {
	local enabled
	config_load uuplugin
	config_get_bool enabled settings enabled 0

	if [ "$enabled" = "1" ] && [ -x "$UUPLUGIN_BIN" ]; then
		procd_open_instance
		procd_set_param command "$UUPLUGIN_BIN"
		procd_set_param pidfile "$UUPLUGIN_PID"
		procd_set_param respawn 3600 5 600
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
		sync_version
	else
		procd_open_instance
		procd_set_param command /bin/busybox sleep 365d
		procd_close_instance
	fi
}

reload_service() {
	restart
}

stop_service() {
	uci set uuplugin.status.running='0'
	uci commit uuplugin
}

boot() {
	uci set uuplugin.status.running='0'
	uci commit uuplugin
}

service_triggers() {
	procd_add_reload_trigger "uuplugin"
}
