include $(TOPDIR)/rules.mk

LUCI_TITLE:=客户端带宽限速
LUCI_DEPENDS:=+luci-base +nftables +kmod-nft-core

PKG_LICENSE:=Apache-2.0
PKG_VERSION:=1.0.0
PKG_RELEASE:=1
PKG_MAINTAINER:=OpenWrt Developer

include ../../feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
